Repository planetarium/Corvette, pull requests merged in 2023-07, with the labels that each got.

#25 Fix incorrect number parse in testWebhookReceiver
  testWebhookReceiver.ts
Labels: Extra Small

#26 Fix webhook test message format
  api.ts
Labels: Extra Small

#19 session based auth in fresh
  api.ts
  constants.ts
  deno.lock
  prisma/schema.prisma
  runHelpers.ts
  web/deno.json
  web/dev.ts
  web/fresh.gen.ts
  web/islands/ListAbi.tsx
  web/islands/ListSources.tsx
  web/islands/ListWebhook.tsx
  web/islands/Login.tsx
  web/main.ts
  web/routes/_404.tsx
  web/routes/_middleware.ts
  web/routes/abi.tsx
  web/routes/api/abi.ts
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/routes/api/sources.ts
  web/routes/api/sources/testWebhook.ts
  web/routes/api/webhook.ts
  web/routes/index.ts
  web/routes/login.tsx
  web/routes/sources.tsx
  web/routes/webhook.tsx
  web/util.ts
Labels: Extra Large

#28 Github Actions workflow for docker images publish
  .dockerignore
  .github/workflows/publish-docker.yml
  Dockerfile
  docker-compose.yml
Labels: Small

#36 Fix argon2 wasm load bug with shim
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/util.ts
Labels: Extra Small

#32 Use single watch for all sources
  observer.ts
Labels: Medium

#35 Fix docker image for web after api port
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  web/main.ts
  web/routes/abi.tsx
  web/routes/sources.tsx
  web/routes/webhook.tsx
  web/util.ts
Labels: Small

#31 Remove double API call on blockTag
  emitter.ts
Labels: Medium

#37 Remove lockfile re-introduced in b43f0b5
  deno.lock
Labels: No Changes
