Repository planetarium/Corvette, pull requests merged in 2023-08, with the labels that each got.

#41 Enable prisma-wrapper to use prereleases
  scripts/prisma-wrapper.ts
Labels: Extra Small

#40 Enable multiple observer
  observer.ts
  prisma-shim.ts
  runHelpers.ts
  web/util.ts
Labels: Small

#38 Dropdown UI & Error toast for Web UI
  web/components/Modal.tsx
  web/components/Toast.tsx
  web/fresh.gen.ts
  web/islands/ListAbi.tsx
  web/islands/ListSources.tsx
  web/islands/ListWebhook.tsx
  web/islands/SearchDropdown.tsx
  web/routes/api/abi.ts
Labels: Large

#45 Use argon2ian instead of npm:argon2-browser
  web/argon2.ts
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/util.ts
Labels: Medium

#43 Bare implementation of event API
  EventResponse.ts
  api.ts
  apiSchema.ts
  emitter.ts
Labels: Large

#42 Logging
  .env.defaults
  .env.example
  api.ts
  app.ts
  constants.ts
  control.ts
  dataproxy.ts
  deno.jsonc
  emitter.ts
  envUtils.ts
  generate-cert.ts
  logUtils.ts
  observer.ts
  runHelpers.ts
  sample/seed-prisma.ts
  scripts/prisma-studio.ts
  testWebhookReceiver.ts
  web/deno.json
  web/main.ts
  web/routes/_404.tsx
  web/routes/_middleware.ts
  web/routes/abi.tsx
  web/routes/api/abi.ts
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/routes/api/sources.ts
  web/routes/api/sources/testWebhook.ts
  web/routes/api/webhook.ts
  web/routes/sources.tsx
  web/routes/webhook.tsx
  web/util.ts
Labels: Extra Large

#46 Fix incorrect logging for Buffers
  emitter.ts
Labels: Extra Small

#49 Housekeeping
  ControlMessage.ts
  control.ts
  emitter.ts
  observer.ts
  prisma/schema.prisma
Labels: Extra Small

#50 web: pass LogLevel to logRequest instead of method, fixed log in web
  web/routes/_404.tsx
  web/routes/_middleware.ts
  web/routes/abi.tsx
  web/routes/api/abi.ts
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/routes/api/sources.ts
  web/routes/api/sources/testWebhook.ts
  web/routes/api/webhook.ts
  web/routes/sources.tsx
  web/routes/webhook.tsx
  web/util.ts
Labels: Medium

#17 Create README.md
  README.md
Labels: Medium

#51 Remove txIndex and reform logs
  EventMessage.ts
  EventResponse.ts
  api.ts
  apiSchema.ts
  emitter.ts
  observer.ts
  prisma/schema.prisma
  web/routes/api/sources/testWebhook.ts
Labels: Small

#54 LOG_LEVEL should have been WARNING
  .env.defaults
  .env.example
Labels: Extra Small

#55 housekeeping
  ControlMessage.ts
  EventMessage.ts
  EventResponse.ts
  abitype.ts
  api.ts
  app.ts
  control.ts
  dataproxy.ts
  decodeEventLog.ts
  deno.jsonc
  emitter.ts
  envUtils.ts
  generate-cert.ts
  logUtils.ts
  moduleUtils.ts
  observer.ts
  prismaSchemaUtils.ts
  runHelpers.ts
  sample/chainDefinitions/goerli.ts
  sample/contracts/deploy-sample-contract.ts
  sample/seed-prisma.ts
  scripts/prisma-wrapper.ts
  scripts/run-with-env.ts
  scripts/signal-reload.ts
  testWebhookReceiver.ts
  web/.vscode/settings.json
  web/argon2.ts
  web/components/AbiTable.tsx
  web/components/Layout.tsx
  web/deno.json
  web/islands/ListAbi.tsx
  web/islands/ListSources.tsx
  web/islands/ListWebhook.tsx
  web/main.ts
  web/routes/_404.tsx
  web/routes/_middleware.ts
  web/routes/abi.tsx
  web/routes/api/abi.ts
  web/routes/api/join.ts
  web/routes/api/login.ts
  web/routes/api/sources.ts
  web/routes/api/sources/testWebhook.ts
  web/routes/api/webhook.ts
  web/routes/login.tsx
  web/routes/sources.tsx
  web/routes/webhook.tsx
  web/util.ts
Labels: Extra Large

#58 Append LogRecord args to defaultLogFormatter
  logUtils.ts
Labels: Extra Small

#61 Fix some logging issues & fmt
  emitter.ts
  observer.ts
  testWebhookReceiver.ts
Labels: Extra Small

#63 Less log for DB for docker compose
  docker-compose.yml
Labels: Extra Small

#62 Remove dataproxy
  .dockerignore
  .env.defaults
  .env.example
  .gitignore
  Dockerfile
  README.md
  app.ts
  dataproxy.ts
  dataproxy/.gitattributes
  dataproxy/.gitignore
  dataproxy/.yarn/patches/prisma-data-proxy-alt-npm-2.0.3-0dedb12737.patch
  dataproxy/.yarn/releases/yarn-3.6.1.cjs
  dataproxy/.yarnrc.yml
  dataproxy/package.json
  dataproxy/yarn.lock
  deno.jsonc
  docker-compose.yml
  envUtils.ts
  generate-cert.ts
  logUtils.ts
  package.json
  prisma/schema.prisma
  prismaSchemaUtils.ts
  scripts/prisma-generate.ts
  scripts/prisma-studio.ts
  scripts/prisma-wrapper.ts
  yarn.lock
Labels: Extra Large

#59 Minimal parametered webhook test interface
  emitter.ts
  web/components/Modal.tsx
  web/fresh.gen.ts
  web/islands/ListSources.tsx
  web/islands/TestWebhookDialog.tsx
  web/routes/api/sources/testWebhook.ts
Labels: Medium

#64 Organize directory structure
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  README.md
  api.ts
  constants/apiSchema.ts
  constants/constants.ts
  decodeEventLog.ts
  deno.jsonc
  dev.ts
  devTools/testWebhookReceiver.ts
  docker-compose.yml
  emitter.ts
  messages/ControlMessage.ts
  messages/EventMessage.ts
  messages/EventResponse.ts
  messages/control.ts
  observer.ts
  prisma/deno.jsonc
  prisma/package.json
  prisma/prisma-wrapper.ts
  prisma/prisma/schema.prisma
  prisma/prismaSchemaUtils.ts
  prisma/shim-inner.ts
  prisma/shim.ts
  prisma/yarn.lock
  sample/chainDefinitions/goerli.ts
  sample/contracts/deploy-sample-contract.ts
  sample/seed-prisma.ts
  scripts/signal-reload.ts
  utils/abiUtils.ts
  utils/concurrencyUtils.ts
  utils/envUtils.ts
  utils/logUtils.ts
  utils/moduleUtils.ts
  utils/runUtils.ts
  utils/uint8ArrayUtils.ts
  web/README.md
  web/main.ts
  web/routes/_middleware.ts
  web/routes/api/abi.ts
  web/routes/api/sources.ts
  web/routes/api/sources/testWebhook.ts
  web/routes/api/webhook.ts
  web/util.ts
Labels: Extra Large

#65 🚀 Release 0.1.0
  CHANGELOG.md
Labels: Extra Small

#66 🚀 Release 0.1.0
  CHANGELOG.md
Labels: Extra Small

#67 🔧 Prepare 0.2.0
  CHANGELOG.md
Labels: Extra Small
